{% set name = "pytest-split" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jerry-git/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ea57791544b034bf4cfae57cf2d036835c4e5a97b0a796da03c974c93106b264

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36 or py>311]

requirements:
  host:
    - python
    - setuptools-scm
    - poetry
    - pip
    - wheel
  run:
    - python
    - pytest >=5.4

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - pytest_split
  commands:
    - pip check
    - pytest --traceconfig | grep pytest-split-{{ version }}
    - pytest -v tests

about:
  home: https://github.com/jerry-git/pytest-split
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin to split tests based on execution time.
  description: |
    pytest plugin which splits the test suite to equally sized "sub suites" based on test execution time.
  doc_url: https://github.com/jerry-git/pytest-split
  dev_url: https://github.com/jerry-git/pytest-split

extra:
  recipe-maintainers:
    - ma-sadeghi
